### ISSUE TITLE
Add show - enter the show data

### ISSUE THREAD

**Issue by MusicSole** [maximinus/grateful-dead-songs#3] opened 2015-12-01 18:10 UTC
Chris, 

Great work - here are two things I found. It will not let me add a 9th tune. I can add a 9th row but I can not get into the box to write out text. 

Also the names of the songs that it is pulling from does not reflect the updates that were made on the master list.  for ex. 'Me and My Uncle' was changed to "Me & My Uncle' but the former is still there.

**Comment by maximinus** [comment] 2015-12-02 02:28
I'm splitting this into 2 issues, so I've removed the bottom part and added to a new issue.

**Comment by maximinus** [comment] 2015-12-02 02:33
Can you tell me what the browser and operating system you use?h I just tried with Linux + Firefox and was easily able to add 15 songs.

**Comment by MusicSole** [comment] 2015-12-02 02:50
Google Chrome. I didn't even think that could have been an issue. Ugh. Sorry to have wasted that time. 

However, will others have that issue on Google Chrome?

**Comment by maximinus** [comment] 2015-12-02 08:43
I'll test on Chrome tomorrow. The code should work on all browsers.

**Comment by maximinus** [comment] 2015-12-10 07:41
This seems to work on Chrome for me. Can you test again? I've tweaked some of the code.

**Comment by maximinus** [comment] 2016-01-04 06:03
Code tested, I'll close this as it seems I can't reproduce with various browsers; plus the code has been changed a lot since the last time this was looked at.

**Closed as completed by maximinus** 2016-01-04 06:03 UTC

**Comment by MusicSole** [comment] 2016-01-04 06:17
Ok. I just put in the first set. Everything ran smoothly. 

Question #1 - why are we not seeing the timings?

**Comment by maximinus** [comment] 2016-01-04 06:21
I don't think the timings are shown anywhere right now. But they are in the database. Look at this page:

http://maximinus.webfactional.com/admin/shows/playedsong/70/

And you'll see a "length" parameter, which is in seconds.
Do you want to see the timings on the pop-up screen that you get when you enter the show?

**Comment by MusicSole** [comment] 2016-01-04 06:30
OK I just wanted to make you aware of it. As long as the data is being taken.
